USE blore0txwork1nobrsy0;

DROP TABLE IF EXISTS VEHICULOS;
DROP TABLE IF EXISTS TIPO_LINEA;
DROP TABLE IF EXISTS TIPO_MARCA;

CREATE TABLE TIPO_MARCA(
    ID_MARCA INT(5) PRIMARY KEY AUTO_INCREMENT,
    DESC_MARCA VARCHAR(200),
    ACTIVO ENUM("S","N")
) ENGINE=INNODB; 

CREATE TABLE TIPO_LINEA(
    ID_LINEA INT(5) PRIMARY KEY AUTO_INCREMENT,
    DESC_LINEA VARCHAR(200),
    ID_MARCA INT(5),
    ACTIVO ENUM("S","N"),
    FOREIGN KEY (ID_MARCA) REFERENCES TIPO_MARCA(ID_MARCA) ON UPDATE CASCADE
) ENGINE=INNODB; 

CREATE TABLE VEHICULOS(
    NRO_PLACA VARCHAR(20) PRIMARY KEY,
    ID_LINEA INT(5),
    MODELO ENUM("1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010",
    "2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"),
    FECHA_VEN_SEGURO DATE,
    FECHA_VEN_TECNOMECANICA DATE,
    FECHA_VEN_CONTRATODO DATE,
    FOREIGN KEY (ID_LINEA) REFERENCES TIPO_LINEA(ID_LINEA) ON UPDATE CASCADE
) ENGINE=INNODB;
/*
    Las tablas pueden llevar campos vacíos por una razón:
    No todos los carros tiene TODOS los datos requeridos en las tablas, 
    por ejemplo, puede que un carro no tenga seguro, por ende, no tiene
    fecha de vencimiento del seguro entonces no tendría qué poner en el campo
    `FECHA_VEN_SEGURO`. Espero comprenda mi análisis, muchas gracias.
*/
INSERT INTO `TIPO_MARCA` (`ID_MARCA`, `DESC_MARCA`, `ACTIVO`) VALUES (NULL, 'DESCRIPCION MARCA', 'S');
INSERT INTO `TIPO_LINEA` (`ID_LINEA`, `DESC_LINEA`, `ID_MARCA`, `ACTIVO`) VALUES (NULL, 'DESCRIPCION LINEA', '1', 'N');
INSERT INTO `VEHICULOS` (`NRO_PLACA`, `ID_LINEA`, `MODELO`, `FECHA_VEN_SEGURO`, `FECHA_VEN_TECNOMECANICA`, `FECHA_VEN_CONTRATODO`) VALUES ('AAA-111', '1', '1999', '2021-01-13', '2021-01-07', '2021-01-12');
SELECT COUNT(NRO_PLACA)FROM VEHICULOS;